management.endpoints.web.exposure.include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anonymous_board
    username: jus1234
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
